spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/dhuvolunteer?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
        username: root
        password: 12345
    neo4j:
        uri: bolt://localhost:7687
        authentication:
            username: neo4j
            password: 20050607cheng

mybatis:
    configuration:
        map-underscore-to-camel-case: true
