spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tradewatch?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
        username: root
        password: 12345
    neo4j:
        uri: bolt://localhost:7687
        authentication:
            username: neo4j
            password: 20050607cheng
    ai:
        openai:
            api-key:  sk-b6278be2badc4f2b83518c6dd71c402b
            base-url: https://api.deepseek.com/v1/
            model: deepseek-chat
    servlet:
        multipart:
            #开启多段上传
            enabled: true
            #最大请求大小
            max-file-size: 30MB
            #最大文件大小
            max-request-size: 30MB

mybatis:
    configuration:
        map-underscore-to-camel-case: true
